# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: black
    name: Format with Black
    entry: poetry run black
    language: system
    types: [python]

  - id: autoflake
    name: autoflake
    entry: poetry run autoflake
    language: system
    types: [python]
    args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]

  - id: flake8
    name: Check with Flake8
    entry: poetry run flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, .]

  # - id: mypy
  #   name: Validate types with MyPy
  #   entry: poetry run mypy
  #   language: system
  #   types: [python]
  #   pass_filenames: false
  #   args:
  #   - "."
