version: '3.0'

networks:
  fastapi_redis_network:
    name: ${DOCKER_NETWORK}
    external: true

volumes:
  redis_data:

services:
  fastapi:
    container_name: ${FASTAPI_CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: ..
      target: development
      dockerfile: ./docker/Dockerfile
    entrypoint: ./docker/docker-entrypoint.sh
    command: bash -c "python -m app"
    volumes:
      - ..:/app
    expose:
      - ${FASTAPI_PORT}
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    networks:
      fastapi_redis_network:
        ipv4_address: ${FASTAPI_HOST}
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: redis
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      fastapi_redis_network:
        ipv4_address: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
